### ISSUE TITLE
[Bug] Cannot autoresize after atom.config.set("file-icons.revealTreeView", false);

### ISSUE THREAD

**Issue by jerrykal** [lexcast/tree-view-autoresize#12]
@lexcast  Here's how to reproduce:

1. Install `file-icons`
2. Open dev console and run 
``` coffeescript
atom.config.set("file-icons.revealTreeView", false);
```
3. Close tree-view, and restart `atom`
4. Open tree-view and you will see the :bug:

**Comment by Alhadis** [comment]
@ooJerryLeeoo It's safe to close this now. I'm still not sure what caused the error, but it doesn't really matter. =)

@lexcast No importa; lo siento. Todo bien.

**Comment by lexcast** [comment]
@ooJerryLeeoo @Alhadis Thank you.
