### ISSUE TITLE
Not work well with atom 1.17.0-beta0

### ISSUE THREAD

**Issue by jerrykal** [lexcast/tree-view-autoresize#13]
@lexcast It's simple to reproduce this :bug: just upgrade atom to `v1.17.0-beta0` and use this package than you'll see the :bug:.

**Comment by lexcast** [comment]
Thank you @ooJerryLeeoo 
I know there are some issues regarding the introduction of Docks.
I will wait to see the tree view and docks in a more stable state, seems still buggy to me.

**Comment by dpren** [comment]
@lexcast broken on 1.16.0 as well. They deprecated jQuery as a dependency, so none of the tree-view jQuery methods work. Are package maintainers given any advanced notice of these sorts of changes?

**Comment by lexcast** [comment]
@dpren 1.16.0 should work. I'm using jQuery directly and not relying on the (now removed) tree-view's jQuery.

**Comment by dpren** [comment]
@lexcast You're right. My packages were just outdated due to this:
* [apm outdated returning undefined when seti-syntax is installed #13790](https://github.com/atom/atom/issues/13790)

**Comment by enoversum** [comment]
Hi @lexcast , no rush, but do you have any idea when this is gonna work again with 1.17.x beta versions? So far it produces problems, even when disabled again (content of tree view pane is restricted).

**Comment by lexcast** [comment]
Hi, I've been working to support docks, you can see that in #14. I will test that for a few days before a release.

**Comment by enoversum** [comment]
@lexcast Oh fine, thanks for letting us know! Love your dedication :) !
