### ISSUE TITLE
Config options not working on 1.17

### ISSUE THREAD

**Issue by betterthanclay** [lexcast/tree-view-autoresize#16]
After upgrading to 1.17 the min width and padding doesn't appear to work any more (unless I'm missing something).
I've worked around it by adding this to my user stylesheet for now, if it helps anyone in the meantime - 

```
atom-dock.left {
    .atom-dock-open {
        .atom-dock-mask {
            min-width: 300px;

            .atom-dock-content-wrapper {
                min-width: 300px;

                .list-tree.full-menu > li > .entries {
                    margin-right: 25px;
                }
            }
        }
    }
}
```

**Comment by Hativ** [comment]
Minimum width doesn't work for me, too.

Seems the minimum width option has been removed.. but why?

**Comment by lexcast** [comment]
I've removed some configs for now. Not sure if I will re-add those.

**Comment by Reducetherisk** [comment]
For me the tree view doesn't slide over far enough to the right to show full file names. 
Not sure if I'm the only one experiencing the issue I'm having.

**Comment by MattKetmo** [comment]
Hello, I noticed the "Maximum Width" field from the settings doesn't not work neither since 1.17

**Comment by lexcast** [comment]
The 2.1.0 release has the settings back.
