### ISSUE TITLE
This package doesn't work on new version of mac atom 1.17.2

### ISSUE THREAD

**Issue by woolson** [lexcast/tree-view-autoresize#19]
Atom Version: 1.17.2 x64
MacOS Version: 10.12.6 Beta (16G12b)
TreeViewAutoResize Version: 2.1.0

19,Jun,2017update: 
 I found it start working today, but i don't know what's going on.

**Comment by danielbayley** [comment]
It has also stopped working on…
macOS: Sierra 10.12.5
Atom: 1.19.0-beta0
tree-view-autoresize: 1.5.0

**Comment by lexcast** [comment]
Hi @woolson, maybe was something with the how atom handles the packages upgrades, not sure, but glad it works now.

Hi @danielbayley, the 1.5.0 version won't work with the newest atom, you should use the 2.1.0.

**Comment by woolson** [comment]
@lexcast thx for your response.

**Comment by danielbayley** [comment]
@lexcast Yeah, it seems to be running fine now, thanks.

**Comment by chad-codes** [comment]
Since this ticket is still open.. it's not working for me either.

macOS: Sierra 10.12.6
Atom: 1.19.3
tree-view-autoresize: 2.2.0

*edit* - it's working now... I haven't used atom in an hour or two, came back, and it's working. No idea.

**Comment by lexcast** [comment]
Maybe it needed to restart atom after the package upgrade.
