### ISSUE TITLE
Does not take effect without re-enabling

### ISSUE THREAD

**Issue by morgandonze** [lexcast/tree-view-autoresize#2]
The package doesn't work on startup; I have to disable and re-enable it.

**Comment by lexcast** [comment]
is the tree-view open on startup?

**Comment by morgandonze** [comment]
No, it is not for me.

**Comment by VasylPosmit** [comment]
+1
Works fine only for project folder.
If open/close other folders, tree width does not reduce.

Nice package, anyway
Thanks

**Comment by lexcast** [comment]
@mlaco hi, this is still an issue for you?

**Comment by morgandonze** [comment]
It work now, thank you!
