### ISSUE TITLE
Using keyboard arrow keys does not trigger auto resize

### ISSUE THREAD

**Issue by ProLoser** [lexcast/tree-view-autoresize#4]
If you focus the tree panel and use left/right to expand/collapse folders, the panel does not auto resize.

![fscuoza3uh](https://cloud.githubusercontent.com/assets/67395/17632733/d014ba26-607e-11e6-8e25-3e0284771c56.gif)

**Comment by lexcast** [comment]
I didn't know I could do that.

I'll investigate on this, thank you
