### ISSUE TITLE
No autoresize when launch the editor without visualization on the tree view. 

### ISSUE THREAD

**Issue by nitram92bcs** [lexcast/tree-view-autoresize#9]
When launch the editor without visualization on the tree view, has not efect of autoresize, You have to applicate the most common solution for everything on the computer science,  **_try to shut down (in this case just close) the application and start it again._**

I suggest you add a if statement which verify the state of tree view before to get the values, or set a trigger when the treeview has been launched, (e.g **ctrl** + **>**)

**Comment by dpren** [comment]
I have an open PR that fixes this.

https://github.com/lexcast/tree-view-autoresize/pull/8
